### PR TITLE
Fix webview reserialization on reload

### LINKED ISSUE #329: Webview reserialization not working
1. open an embedded preview
2. reload the window
3. panel does not restore preview :bug:

### PR DESCRIPTION
**Pull request by andreamah**
Fixes #329

### CODE REVIEW

File: src/manager.ts [hunk 1]
```diff
@@ -184,16 +184,24 @@ export class Manager extends Disposable {
 
 				if (!workspace) {
 					// no workspace; try to decode endpoint to fix file
-					file = this._endpointManager.decodeLooseFileEndpoint(file);
-					if (!file) {
+					const potentialFile = this._endpointManager.decodeLooseFileEndpoint(file);
```
Comment (amunger) [inline src/manager.ts:187]: nit: seems like you could just reassign `file` here and skip adding the `potentialFile` variable

**Review by amunger — APPROVED** [review]

File: src/manager.ts (hunk 1 above)
Comment (andreamah) [reply src/manager.ts:187]: Oh, I just have it like that because I wanted to keep `file` strictly of type string. `potentialFile` is of type string | undefined and it gets checked for undefined before being assigned to `file`
