### PR TITLE
Fixed Functions Printed as Undefined

### LINKED ISSUE #128: Output console prints `undefined` for function objects
Testing microsoft/vscode#129445

Issue Type: <b>Bug</b>

1. Create an html file that logs a function-type object:
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <p>fdsafasd</p>
    <script>
        console.log(() => {})
    </script>
</body>
</html>
```

**Bug**
In the output console, this prints `undefined`

However in the developer tools, this prints `() => {}` instead 

VS Code version: Code - Insiders 1.59.0-insider (c3b4df8f5d9c14aa4cfddb587231d0d52e72e5a2, 2021-07-27T15:07:54.419Z)
OS version: Linux x64 4.15.0-142-generic snap
Restricted Mode: No

### PR DESCRIPTION
**Pull request by davixiao**
resolve #128 @mjbvz @andreamah 
```javascript
JSON.stringify(()=>{}) 
```
produces undefined instead of an error.

Checks if stringifiedMsg is undefined and throw an error.
image

### CODE REVIEW

File: media/injectScript.js [hunk 1]
```diff
@@ -83,6 +83,7 @@ function createConsoleOverride(type) {
 
 		try {
 			stringifiedMsg = JSON.stringify(msg);
+			if (!stringifiedMsg) throw new Error('stringifiedMsg is undefined');
```
Comment (andreamah) [inline media/injectScript.js:86]: `stringifiedMsg` is an internal implementation detail. Although this exception doesn't get surfaced to the top of the stack, maybe a more appropriate message would be "message is not in JSON format"?

**Review by andreamah — COMMENTED** [review]
Thanks for contributing again! Just a small nitpick 😁

File: media/injectScript.js (hunk 1 above)
Comment (davixiao) [reply media/injectScript.js]: Thanks, that makes sense. Let me know if my newest commit works @andreamah

**Review by andreamah — APPROVED** [review]
@davixiao Looks good to me! Thanks for making that change! 🎉🎉😁

@mjbvz can you merge this again? (I feel bad for always bothering you 😭)

**Comment by mjbvz** [comment]
Thanks! Will publish updated ext with the fixes shortly

**Comment by andreamah** [comment]
Thanks! It might also be a good idea to update the CHANGELOG.md when publishing.
