### PR TITLE
isolated listeners into singleton and fixed out-of-workspace refresh

### LINKED ISSUE #264: on changes to saved files setting doesn't work outside of workspace
1. set setting to refresh on save
2. preview an out-of-workspace file
3. saving the file doesn't refresh the preview :bug:

### PR DESCRIPTION
**Pull request by andreamah**
Fixes #264

### CODE REVIEW

File: src/server/serverUtils/statusBarNotifier.ts [hunk 1]
```diff
@@ -58,21 +58,28 @@ export class StatusBarNotifier extends Disposable {
...
-		localize(
-			'livePreviewRunningOnPorts',
-			'Live Preview running on ports: '
-		);
+		portsTooltip =
+			this._ports.size == 1
+				? localize('livePreviewRunningOnPort', 'Live Preview running on port: ')
+				: localize(
+						'livePreviewRunningOnPorts',
+						'Live Preview running on ports: '
```
Comment (roblourens) [inline src/server/serverUtils/statusBarNotifier.ts:81]: I recommend putting the space outside the localized string, it will probably be lost in some translation

File: src/updateListener.ts [hunk 2]
```diff
@@ -0,0 +1,130 @@
+import { Disposable } from "./utils/dispose";
```
Comment (roblourens) [inline src/updateListener.ts:1]: All of your source files need copyright headers at the top, I didn't notice that before: https://docs.opensource.microsoft.com/releasing/maintain/copyright-headers/

**Review by roblourens — APPROVED** [review]

**Review by roblourens — APPROVED** [review]
